app.name: tbk-bitcoin-spring-boot-starter-demo
app.description: A spring boot bitcoin demo application

spring.application.name: 'tbk-bitcoin-spring-boot-starter-demo'
spring.http.log-request-details: false

server.port: 8080
server.compression.enabled: true

management.server.port: 9001

# LOGGING
logging.file.path: ./var/log
logging.file.name: application.log
logging.config: classpath:logback.xml
logging.level.org.springframework: INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
#logging.level.web: DEBUG

org.tbk.spring.testcontainer.tor:
  enabled: true
  hidden-services:
    my_spring_application_8080:
      virtual-port: 80
      host-port: 8080
  environment:
    TOR_EXTRA_ARGS: |
      # no exits allowed
      ExitPolicy reject *:*
      ## If you enable the controlport, be sure to enable a authentication method
      CookieAuthentication 1
