app.name: tbk-bitcoin-spring-boot-starter-demo
app.description: A spring boot bitcoin demo application

spring.application.name: 'tbk-bitcoin-spring-boot-starter-demo'
spring.http.log-request-details: false

server.port: 8080
server.use-forward-headers: true
server.compression.enabled: true

management.server.port: 9001

# LOGGING
logging.file.path: ./var/log
logging.file.name: application.log
logging.config: classpath:logback.xml
logging.level.org.springframework: INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
logging.level.org.tbk.bitcoin.regtest: DEBUG

org.tbk.bitcoin.regtest.enabled: false

org.tbk.bitcoin.jsonrpc:
  network: mainnet
  rpchost: http://localhost
  rpcport: 8332
  rpcuser: my-bitcoin-rpc-user
  rpcpassword: my-bitcoin-rpc-password

org.tbk.bitcoin.zeromq:
  network: mainnet
  zmqpubrawblock: tcp://127.0.0.1:28332
  zmqpubrawtx: tcp://127.0.0.1:28333
  zmqpubhashblock: tcp://127.0.0.1:28334
  zmqpubhashtx: tcp://127.0.0.1:28335

org.tbk.bitcoin.electrum-daemon.jsonrpc:
  enabled: true
  rpchost: http://localhost
  rpcport: 7000
  rpcuser: my-electrum-rpc-user
  rpcpassword: my-electrum-rpc-password
